[book]
authors = ["qaqland", "ArielAxionL"]
language = "zh-CN"
src = "docs"
title = "The Wayland Protocol 中文版"
description = "The Wayland Protocol 中文版"

[output.html]
git-repository-url = "https://github.com/ArkToria/the_wayland_protocol_zh_CN"
edit-url-template = "https://github.com/ArkToria/the_wayland_protocol_zh_CN/edit/main/{path}"
